#!/bin/bash -       
#title           	:install_conf
#description     	:Script to install custom linux
#author		 	:greg
#date            	:01-21-2015
#==============================================================================
cp .bashrc $HOME/
cp .bash_aliases $HOME/
cp -r bin/ $HOME/
cp .inputrc $HOME/
if [[ ! -f $HOME/.config/terminator ]]; then
    mkdir $HOME/.config/terminator
fi
cp terminator_config $HOME/.config/terminator/
source $HOME/.bashrc

