#!/bin/bash -       
#title           	:install_conf
#description     	:Script to install custom linux
#author		 	:greg
#date            	:01-21-2015
#==============================================================================
ln -s .bashrc $HOME/.bashrc
ln -s .bash_aliases $HOME/.bash_aliases
ln -s bin/ $HOME/bin
ln -s .inputrc $HOME/.inputrc
if [[ ! -f $HOME/.config/terminator ]]; then
    mkdir $HOME/.config/terminator
fi
ln -s terminator_config $HOME/.config/terminator/config
source $HOME/.bashrc

