#!/bin/bash -       
#title           	:install_sys
#description     	:install all the desired packages, but will not configure
#author		 		:greg
#date            	:today
#==============================================================================
# List of packages to install :
# git
# Dropbox
# vim, 
# Chromium, qt, build-essential, cmake, make
# Terminator, mplayer, python34-pip 
# 
